import type { AppProps } from 'next/app'
import { Provider } from 'react-redux'
import React from 'react';

import store from '../redux'
import Modal from '../components/Modal';

import '../styles/index.scss'
import MenuButton from '../components/MenuButton';
import LoginButton from '../components/LoginButton';
import Sidebar from '../components/Sidebar';
import Head from 'next/head';


const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
      <Provider store={store}>
        <Head>
          <title>Light Song</title>
          {/* <meta name="description" content="Generated by create next app" /> */}
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
        <LoginButton />
        <MenuButton />
        <Sidebar />
        <Modal />
      </Provider>
  )
}

export default React.memo(MyApp);

