import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect } from 'react'
import LoginButton from '../components/LoginButton'
import styles from '../styles/pages/home.module.scss'

const Home = (data: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Light Song</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LoginButton />
        <Link href="/songlist">Song List</Link>
        <div>{} : Provided props</div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

// This gets called on every request
export async function getServerSideProps (context: any) {
  // Fetch data from external API
  // const res = await fetch(`https://.../data`)
  // const data = await res.json()
// console.log(context)
  // Pass data to the page via props
  return { props: { data: 'Provided is working' } }
}

export default Home
