import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect } from 'react'

const Home = (data: any) => {

  // const renderContent = () => {
  //   switch() {
  //     case ""
  //     deafult
  //   }
  // }

  // useEffect(()=>{
  //   console.log(data)
  // })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/songlist">Song List</Link>
        <Link href="/login">Login page</Link>
        <div>{} : Provided props</div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

// This gets called on every request
export async function getServerSideProps(context: any) {
  // Fetch data from external API
  // const res = await fetch(`https://.../data`)
  // const data = await res.json()
// console.log(context)
  // Pass data to the page via props
  return { props: { data: "Provided is working" } }
}

export default Home
